// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQz_JQwf3-bWraNYwtHC6El0BFcMhRCpg',
    appId: '1:683537507410:web:740c93375c1e5f4b942b8b',
    messagingSenderId: '683537507410',
    projectId: 'food-app-a210b',
    authDomain: 'food-app-a210b.firebaseapp.com',
    storageBucket: 'food-app-a210b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMrGp3f5hteH0A9uFcEXskKKq8mZTE3hE',
    appId: '1:683537507410:android:1fe76f68ad7e537f942b8b',
    messagingSenderId: '683537507410',
    projectId: 'food-app-a210b',
    storageBucket: 'food-app-a210b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqSWLBRGBXFk3yMIyQywjW7gLGdXdTxOA',
    appId: '1:683537507410:ios:d0fe0d03e911f4b1942b8b',
    messagingSenderId: '683537507410',
    projectId: 'food-app-a210b',
    storageBucket: 'food-app-a210b.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );
}
